<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2019-03-18 16:17:32
 */
return [
    \yii\web\JqueryAsset::class => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
        ],
    ],
    'yii\\web\\YiiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
        ],
    ],
    'yii\\widgets\\ActiveFormAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
        ],
    ],
    'yii\\validators\\ValidationAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
        ],
    ],
    \yii\bootstrap\BootstrapAsset::class => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
        ],
    ],
    \yii\bootstrap\BootstrapPluginAsset::class => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
        ],
    ],
    \common\assets\BootstrapSelectAsset::class => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
        ],
    ],
    \kartik\rating\StarRatingAsset::class => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
        ],
    ],
    \kartik\base\WidgetAsset::class => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
        ],
    ],
    /*\themes\sakura\assets\SakuraThemeAsset::class => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
        ],
    ],*/

    \yii\jui\JuiAsset::class => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
        ],
    ],
];