<?php

/**
 * @author Nurbek Nurjanov nurbek.nurjanov@mail.ru
 * @link http://sakuracommerce.com/
 * @copyright Copyright (c) 2018 Sakuracommerce
 * @license http://sakuracommerce.com/license/
 */

namespace extended\application;


class Application extends \yii\web\Application
{
    public function __isset($name)
    {
        if($name=='reCaptcha')
            return true;
        return parent::__isset($name); // TODO: Change the autogenerated stub
    }
}